[build-system]
requires = ["setuptools>=42", "wheel", "pybind11>=2.6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "calculator"
version = "1.0.0"
requires-python = ">=3.6"
description = "Pybind11 示例：计算器模块"
readme = "README.md"

